### ISSUE TITLE
Khoj error with LiteLLM and GROQ

### ISSUE THREAD

**Issue by stevennt** [stevennt/myai.abn.khoj.old.abandon#33]
![image](https://github.com/stevennt/myai.abn.khoj/assets/32351181/c62efeda-62b7-4093-b70e-4b64eaefc9f8)

**Comment by stevennt** [comment]
BadRequestError: Error code: 400 - {'error': {'message': "litellm.BadRequestError: BadRequestError: GroqException - Error code: 400 - {'error': {'message': 'response_format` does not support streaming', 'type': 'invalid_request_error'}}",

![image](https://github.com/stevennt/myai.abn.khoj/assets/32351181/800dd18f-67a8-4514-a13e-9bcd7a67f8af)

**Comment by stevennt** [comment]
Seems like it's a GROG problem: https://github.com/langchain-ai/langchain/issues/23629

**Comment by stevennt** [comment]
I missed the step 5: 
![image](https://github.com/stevennt/myai.abn.khoj/assets/32351181/1403d832-92ab-4fa2-ad38-a722c43d783b)

![image](https://github.com/stevennt/myai.abn.khoj/assets/32351181/e93575c8-c3d3-4a6d-8c11-4102ddd22162)

**Comment by stevennt** [comment]
abnkhoj-1          | [01:55:56.125458] DEBUG    uvicorn.error: < TEXT 'Will this     protocol.py:1172
abnkhoj-1          |                            crash the server?' [27 bytes]                        
abnkhoj-1          | [01:55:56.131573] DEBUG    uvicorn.error: > TEXT '{"type":      protocol.py:1178
abnkhoj-1          |                            "status", "message":                                 
abnkhoj-1          |                            "**Understanding ...e":                              
abnkhoj-1          |                            "application/json"}' [121 bytes]                     
abnkhoj-1          | [01:55:56.137727] WARNING  khoj.processor.conversation.utils:       utils.py:217
abnkhoj-1          |                            Fallback to default chat model                       
abnkhoj-1          |                            tokenizer: None.                                     
abnkhoj-1          |                            Configure tokenizer for unsupported                  
abnkhoj-1          |                            model: llama3-70b-8192 in settings to                
abnkhoj-1          |                            improve context stuffing.                            
abnkhoj-1          | [01:55:56.410336] DEBUG    khoj.processor.conversation.openai before_sleep.py:65
abnkhoj-1          |                            .utils: Retrying                                     
abnkhoj-1          |                            khoj.processor.conversation.openai                   
abnkhoj-1          |                            .utils.completion_with_backoff in                    
abnkhoj-1          |                            0.8983713578955119 seconds as it                     
abnkhoj-1          |                            raised BadRequestError: Error                        
abnkhoj-1          |                            code: 400 - {'error': {'message':                    
abnkhoj-1          |                            'response_format` does not support                   
abnkhoj-1          |                            streaming', 'type':                                  
abnkhoj-1          |                            'invalid_request_error'}}.                           
abnkhoj-1          | [01:55:57.507571] DEBUG    khoj.processor.conversation.openai before_sleep.py:65
abnkhoj-1          |                            .utils: Retrying                                     
abnkhoj-1          |                            khoj.processor.conversation.openai                   
abnkhoj-1          |                            .utils.completion_with_backoff in                    
abnkhoj-1          |                            1.455995355052044 seconds as it                      
abnkhoj-1          |                            raised BadRequestError: Error                        
abnkhoj-1          |                            code: 400 - {'error': {'message':                    
abnkhoj-1          |                            'response_format` does not support                   
abnkhoj-1          |                            streaming', 'type':                                  
abnkhoj-1          |                            'invalid_request_error'}}.                           
abnkhoj-1          | [01:55:59.162003] DEBUG    khoj.routers.helpers: Chat actor:      helpers.py:175
abnkhoj-1          |                            Infer information sources to refer:

**Comment by stevennt** [comment]
![image](https://github.com/stevennt/myai.abn.khoj/assets/32351181/3a3c7c67-fc29-4b76-8397-68ef6fa7bb04)

![image](https://github.com/stevennt/myai.abn.khoj/assets/32351181/684fd2dd-bab6-4722-8b85-4d0d579938b6)

**Comment by stevennt** [comment]
why is this None?

![image](https://github.com/stevennt/myai.abn.khoj/assets/32351181/f6bc2a11-7b25-47a3-b0f8-a7c916c2270a)

**Comment by stevennt** [comment]
with real OpenAi, it shows this:

![image](https://github.com/stevennt/myai.abn.khoj/assets/32351181/07304194-e50e-4bd6-a353-3f060b4dee7f)

**Comment by stevennt** [comment]
Tokenizer: Do not set for OpenAI, mistral, llama3 based models

<img width="979" alt="image" src="https://github.com/stevennt/myai.abn.khoj/assets/32351181/1038ae84-475d-4f1f-b593-7e404759bec7">

**Comment by stevennt** [comment]
<img width="858" alt="image" src="https://github.com/stevennt/myai.abn.khoj/assets/32351181/e59e130b-e1fe-4960-a47c-289a6e151381">

**Comment by stevennt** [comment]
How/where to set this stream=True?

**Comment by stevennt** [comment]
LiteLLM said something: 
 21:13:49 - LiteLLM:ERROR: main.py:400 - litellm.acompletion(): Exception occured - Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01hz1yy379fs98dfe35nxzg4dv` on tokens per minute (TPM): Limit 6000, Used 0, Requested 11385. Please try again in 53.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 968, in async_streaming
litellm-1  |     response = await openai_aclient.chat.completions.create(
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1181, in create
litellm-1  |     return await self._post(
litellm-1  |            ^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1790, in post
litellm-1  |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
litellm-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1493, in request
litellm-1  |     return await self._request(
litellm-1  |            ^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1584, in _request
litellm-1  |     raise self._make_status_error_from_response(err.response) from None
litellm-1  | openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01hz1yy379fs98dfe35nxzg4dv` on tokens per minute (TPM): Limit 6000, Used 0, Requested 11385. Please try again in 53.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
litellm-1  | 
litellm-1  | During handling of the above exception, another exception occurred:
litellm-1  | 
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 379, in acompletion
litellm-1  |     response = await init_response
litellm-1  |                ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 991, in async_streaming
litellm-1  |     raise OpenAIError(status_code=e.status_code, message=str(e))
litellm-1  | litellm.llms.openai.OpenAIError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01hz1yy379fs98dfe35nxzg4dv` on tokens per minute (TPM): Limit 6000, Used 0, Requested 11385. Please try again in 53.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
litellm-1  | 
litellm-1  | 21:13:51 - LiteLLM Proxy:ERROR: proxy_server.py:3141 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.RateLimitError: RateLimitError: GroqException - Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01hz1yy379fs98dfe35nxzg4dv` on tokens per minute (TPM): Limit 6000, Used 0, Requested 11385. Please try again in 53.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}} LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 968, in async_streaming
litellm-1  |     response = await openai_aclient.chat.completions.create(
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1181, in create
litellm-1  |     return await self._post(
litellm-1  |            ^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1790, in post
litellm-1  |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
litellm-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1493, in request
litellm-1  |     return await self._request(
litellm-1  |            ^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1584, in _request
litellm-1  |     raise self._make_status_error_from_response(err.response) from None
litellm-1  | openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01hz1yy379fs98dfe35nxzg4dv` on tokens per minute (TPM): Limit 6000, Used 0, Requested 11385. Please try again in 53.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
litellm-1  | 
litellm-1  | During handling of the above exception, another exception occurred:
litellm-1  | 
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 379, in acompletion
litellm-1  |     response = await init_response
litellm-1  |                ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 991, in async_streaming
litellm-1  |     raise OpenAIError(status_code=e.status_code, message=str(e))
litellm-1  | litellm.llms.openai.OpenAIError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01hz1yy379fs98dfe35nxzg4dv` on tokens per minute (TPM): Limit 6000, Used 0, Requested 11385. Please try again in 53.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
litellm-1  | 
litellm-1  | During handling of the above exception, another exception occurred:
litellm-1  | 
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3043, in chat_completion
litellm-1  |     responses = await llm_responses
litellm-1  |                 ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 643, in acompletion
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 631, in acompletion
litellm-1  |     response = await self.async_function_with_fallbacks(**kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2315, in async_function_with_fallbacks
litellm-1  |     raise original_exception
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2160, in async_function_with_fallbacks
litellm-1  |     response = await self.async_function_with_retries(*args, **kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2415, in async_function_with_retries
litellm-1  |     raise original_exception
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2337, in async_function_with_retries
litellm-1  |     response = await original_function(*args, **kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 773, in _acompletion
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 745, in _acompletion
litellm-1  |     response = await _response
litellm-1  |                ^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1442, in wrapper_async
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1270, in wrapper_async
litellm-1  |     result = await original_function(*args, **kwargs)
litellm-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 407, in acompletion
litellm-1  |     raise exception_type(
litellm-1  |           ^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 7503, in exception_type
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 5914, in exception_type
litellm-1  |     raise RateLimitError(
litellm-1  | litellm.exceptions.RateLimitError: litellm.RateLimitError: RateLimitError: GroqException - Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_01hz1yy379fs98dfe35nxzg4dv` on tokens per minute (TPM): Limit 6000, Used 0, Requested 11385. Please try again in 53.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}} LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
litellm-1  | 
litellm-1  | 21:13:51 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
litellm-1  | INFO:     172.19.0.11:57350 - "POST /chat/completions HTTP/1.1" 429 Too Many Requests
litellm-1  | 21:13:54 - LiteLLM Proxy:ERROR: proxy_server.py:3141 - litellm.proxy.proxy_server.chat_completion(): Exception occured - No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-llama3-70b-8192. pre-call-checks=False, allowed_model_region=n/a
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3043, in chat_completion
litellm-1  |     responses = await llm_responses
litellm-1  |                 ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 643, in acompletion
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 631, in acompletion
litellm-1  |     response = await self.async_function_with_fallbacks(**kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2315, in async_function_with_fallbacks
litellm-1  |     raise original_exception
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2160, in async_function_with_fallbacks
litellm-1  |     response = await self.async_function_with_retries(*args, **kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2415, in async_function_with_retries
litellm-1  |     raise original_exception
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2337, in async_function_with_retries
litellm-1  |     response = await original_function(*args, **kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 773, in _acompletion
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 660, in _acompletion
litellm-1  |     deployment = await self.async_get_available_deployment(
litellm-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 4791, in async_get_available_deployment
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 4688, in async_get_available_deployment
litellm-1  |     raise ValueError(
litellm-1  | ValueError: No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-llama3-70b-8192. pre-call-checks=False, allowed_model_region=n/a
litellm-1  | 
litellm-1  | 21:13:54 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
litellm-1  | INFO:     172.19.0.11:57350 - "POST /chat/completions HTTP/1.1" 429 Too Many Requests
litellm-1  | 21:13:57 - LiteLLM Proxy:ERROR: proxy_server.py:3141 - litellm.proxy.proxy_server.chat_completion(): Exception occured - No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-llama3-70b-8192. pre-call-checks=False, allowed_model_region=n/a
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3043, in chat_completion
litellm-1  |     responses = await llm_responses
litellm-1  |                 ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 643, in acompletion
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 631, in acompletion
litellm-1  |     response = await self.async_function_with_fallbacks(**kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2315, in async_function_with_fallbacks
litellm-1  |     raise original_exception
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2160, in async_function_with_fallbacks
litellm-1  |     response = await self.async_function_with_retries(*args, **kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2415, in async_function_with_retries
litellm-1  |     raise original_exception
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2337, in async_function_with_retries
litellm-1  |     response = await original_function(*args, **kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 773, in _acompletion
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 660, in _acompletion
litellm-1  |     deployment = await self.async_get_available_deployment(
litellm-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 4791, in async_get_available_deployment
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 4688, in async_get_available_deployment
litellm-1  |     raise ValueError(
litellm-1  | ValueError: No deployments available for selected model, Try again in 60 seconds. Passed model=gpt-llama3-70b-8192. pre-call-checks=False, allowed_model_region=n/a
litellm-1  | 
litellm-1  | 21:13:57 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
litellm-1  | INFO:     172.19.0.11:57350 - "POST /chat/completions HTTP/1.1" 429 Too Many Requests

**Comment by stevennt** [comment]
The error messages you're encountering indicate a rate limit issue with the Groq API for the llama3-70b-8192 model. Here's a breakdown of the problem and some potential solutions:

1. Rate Limit Exceeded:
   The primary error is a rate limit (429 Too Many Requests) from Groq:

   "Rate limit reached for model `llama3-70b-8192` in organization `org_01hz1yy379fs98dfe35nxzg4dv` on tokens per minute (TPM): Limit 6000, Used 0, Requested 11385. Please try again in 53.85s."

2. Token Usage:
   Your request is trying to use 11,385 tokens, which exceeds the 6,000 tokens per minute (TPM) limit for your account.

3. Subsequent Errors:
   After the initial rate limit error, the system tries to use alternative deployments but finds none available, leading to "No deployments available" errors.

To address these issues, consider the following approaches:

1. Reduce Token Usage:
   Try to reduce the number of tokens in your requests. This might involve shortening your prompts or breaking larger requests into smaller chunks.

2. Implement Rate Limiting:
   Add rate limiting in your application to ensure you don't exceed 6,000 tokens per minute. This could involve queuing requests or adding delays between calls.

3. Retry Logic:
   Implement a retry mechanism with exponential backoff. When you receive a 429 error, wait for the suggested time (in this case, 53.85 seconds) before retrying.

4. Increase Rate Limits:
   If possible, contact Groq to inquire about increasing your rate limits.

5. Use Multiple Models:
   Configure your application to use alternative models when one hits rate limits. This could help distribute the load.

6. Optimize Streaming:
   If you're using streaming, ensure it's implemented efficiently to avoid unnecessary token usage.

7. Monitor Usage:
   Implement monitoring to track your token usage and adjust your requests accordingly.

To modify your configuration, you might want to add rate limiting parameters:

```yaml
model_list:
  - model_name: llama3-70b-8192
    litellm_params:
      model: groq/llama3-70b-8192
      api_key: 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
      api_base: https://api.groq.com/openai/v1
      api_version: "v1"
      stream: True
      max_retries: 5
      request_timeout: 60
```

Consider adding a `tpm` (tokens per minute) limit in your LiteLLM configuration if it supports this feature. Also, ensure your application has proper error handling to deal with rate limit errors gracefully.

**Comment by stevennt** [comment]
Khoj and LiteLLM doesn't get along very well.
Lots of error showing in LiteLLM backend.
Khoj frontend hangs.
At the same time I could call LiteLLM on commandline and it runs. 
curl -X POST https://llm.abnasia.org/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-Q8hmPzR9Pb80ihYL" \
  -d '{
    "model": "gpt-llama3-70b-8192",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello, how are you?"
      }
    ],
  }'

<img width="1440" alt="image" src="https://github.com/stevennt/myai.abn.khoj/assets/32351181/fd481af8-4b98-48fb-a799-23df22a7a8b3">
<img width="1440" alt="image" src="https://github.com/stevennt/myai.abn.khoj/assets/32351181/63583cfe-f7a2-4151-a6d5-a588a4a50537">
<img width="759" alt="image" src="https://github.com/stevennt/myai.abn.khoj/assets/32351181/0f133718-9405-4c79-bce6-7d3408bb98b5">

**Comment by stevennt** [comment]
So /notes only worked with OpenAi so far.
Not with LiteLLM, not with Grog, not even when local model I download (this model could answer with /general)

<img width="1440" alt="image" src="https://github.com/stevennt/myai.abn.khoj/assets/32351181/0a0b7bd6-e8e6-4b59-bd24-bea54851b53a">
<img width="1440" alt="image" src="https://github.com/stevennt/myai.abn.khoj/assets/32351181/ec5b5af7-bfc7-4c07-91df-45d8c3fa0c68">

**Comment by stevennt** [comment]
<img width="1440" alt="image" src="https://github.com/stevennt/myai.abn.khoj/assets/32351181/0ef4fbee-8c7a-41be-9944-3336a03fae4d">
